name: Listing S3 Buckets


on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  listing_buckets:
    runs-on: ubuntu-latest

    steps:
      - name: SET Up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.IAM_REGION }}

      - name: List S3 Buckets
        env:
          aws-region: ${{ secrets.IAM_REGION }}
        run: |
         echo "Listing S3 Buckets"
         aws s3 ls

